### ISSUE TITLE
Pro MiFlora ein ESP32?

### ISSUE THREAD

**Issue by SanwebGit** [RonnyWinkler/esp32.miflora#1]
Wollte einmal nachhaken, ob pro MiFlora ein ESP32 benötigt wird oder ob der ESP32 mehrere MiFlora's verwalten kann ...

**Comment by RonnyWinkler** [comment]
Es wird nur ein ESP benötigt. Die MiFloras werden in der Datei condig.h in das Array eingetragen. Vorher natürlich die Vorlagedatei kopieren und nach config.h umbenennen und bearbeiten - auch die weiteren EInstellungen wie WLAN/MQTT anpassen.

// array of different xiaomi flora MAC addresses
char* FLORA_DEVICES[] = {
    "C4:7C:8D:67:11:11", 
    "C4:7C:8D:67:22:22", 
    "C4:7C:8D:67:33:33"
};

Hier können beliebig viele Bluetoohs-MAC-Adressen eingetragen werden. Die Adressen muss man mit einem BT-Scanner ermitteln, z.B. https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner

Je MAC wird ein MQTT Topic erstellt mit den darin enthaltenen Werten.
